/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Copyright 2026 Xenia Canary. All rights reserved.                          *
 * Released under the BSD license - see LICENSE in the root for more details. *
 ******************************************************************************
 */

#ifndef XENIA_APP_LOCALIZATION_H_
#define XENIA_APP_LOCALIZATION_H_

#include <cstdint>

namespace xe::app::localization {

enum class Language : uint8_t {
  kEnglish,
  kTraditionalChinese,
};

// Stable identifiers keep translations independent of the English wording.
enum class StringId : uint16_t {
  kMenuFile,
  kMenuOpenRecent,
  kMenuZarPackage,
  kMenuOpen,
  kMenuInstallContent,
  kMenuCreate,
  kMenuExtract,
  kMenuClose,
  kMenuShowContentDirectory,
  kMenuExit,
  kMenuProfile,
  kMenuShowProfile,
  kMenuContent,
  kContentInstall,
  kContentExtract,
  kContentShowInstalled,
  kMenuCpu,
  kMenuResetTimeScalar,
  kMenuHalfTimeScalar,
  kMenuDoubleTimeScalar,
  kMenuToggleProfiler,
  kMenuPauseProfiler,
  kMenuGuestDebugger,
  kMenuHostDebugger,
  kMenuGpu,
  kMenuTraceFrame,
  kMenuClearRuntimeCaches,
  kMenuDisplay,
  kMenuPostProcessing,
  kMenuFullscreen,
  kMenuScreenshot,
  kMenuKbm,
  kMenuKbmSettings,
  kMenuHid,
  kMenuControllerVibration,
  kMenuControllerHotkeys,
  kMenuXmp,
  kMenuShowXmp,
  kMenuConsole,
  kMenuConsoleSettings,
  kMenuUi,
  kMenuInterfaceLanguage,
  kLanguageEnglish,
  kLanguageEnglishActive,
  kLanguageTraditionalChinese,
  kLanguageTraditionalChineseActive,
  kMenuHelp,
  kMenuFaq,
  kMenuCompatibility,
  kMenuForkBuildCommit,
  kMenuUpstreamBaseCommit,
  kMenuRecentChanges,
  kMenuAbout,

  kXmpTitle,
  kXmpStatus,
  kXmpIdle,
  kXmpPaused,
  kXmpPlaying,
  kXmpPause,
  kXmpResume,
  kXmpVolume,

  kProfileTitle,
  kProfileNoProfilesTitle,
  kProfileNoProfilesMessage,
  kProfileCreate,
  kProfileCreateMigrate,
  kProfileOpenMenu,
  kProfileNoProfiles,
  kProfileLogin,
  kProfileLoginToSlot,
  kProfileSlot,
  kProfileLogout,
  kProfileModify,
  kProfilePlayedTitles,
  kProfileContentDirectory,
  kProfileDelete,
  kProfileDeleteWarning,
  kProfileConfirmDelete,
  kProfileUser,
  kProfileAssignedSlot,
  kProfileNotSignedIn,

  kPostTitle,
  kPostAnyGpu,
  kPostAntiAliasing,
  kPostNone,
  kPostFxaaNormal,
  kPostFxaaExtreme,
  kPostResamplingSharpening,
  kPostNoneBilinear,
  kPostCas,
  kPostFsr,
  kPostBilinearDescription,
  kPostCasDescription,
  kPostFsrDescription,
  kPostFxaaRecommended,
  kPostFsrSharpnessReduction,
  kPostCasSharpnessFsr,
  kPostCasSharpness,
  kPostReset,
  kPostDithering,
  kPostDither8bpc,

  kKbmTitle,
  kKbmBackendInactive,
  kKbmPressBinding,
  kKbmBindingTooltip,
  kKbmAddAlternativeBinding,
  kKbmClearBinding,
  kKbmKeyboard,
  kKbmEnableController,
  kKbmControllerSlot,
  kKbmPlayer1,
  kKbmPlayer2,
  kKbmPlayer3,
  kKbmPlayer4,
  kKbmBindingHelp,
  kKbmXboxInput,
  kKbmKeyboardMouse,
  kKbmMouse,
  kKbmEnableRawMouse,
  kKbmRawMouseRequiresController,
  kKbmSensitivity,
  kKbmSensitivityGuide,
  kKbmInvertVertical,
  kKbmCaptureOnStart,
  kKbmCaptureToggle,
  kKbmFineTuning,
  kKbmAimCurve,
  kKbmAimCurveHelp,
  kKbmMouseSmoothing,
  kKbmMouseSmoothingHelp,
  kKbmCompensateGameDeadzone,
  kKbmMinimumResponse,
  kKbmMinimumResponseHelp,
  kKbmFullStickThreshold,
  kKbmFullStickHelp,
  kKbmDiagnostics,
  kKbmLastStickOutput,
  kKbmMaximum,
  kKbmRawSpeed,
  kKbmRawInputStatus,
  kKbmReady,
  kKbmOn,
  kKbmOff,
  kKbmActive,
  kKbmReleased,
  kKbmInputPaused,
  kKbmDiagnosticsUnavailable,
  kKbmSave,
  kKbmCancel,
  kKbmResetAll,
  kKbmSettingsFile,
  kKbmSaveFailed,
  kKbmSaveClose,
  kKbmDirty,
  kKbmSaved,
  kKbmUnbound,
  kKbmBindEscape,
  kKbmCancelCapture,
  kKbmSnapshot,
  kKbmInputSampling,
  kKbmStartInputSampling,
  kKbmStopAndSaveInputSampling,
  kKbmCancelInputSampling,
  kKbmInputSamplingHelp,
  kKbmInputSamplingProgress,
  kKbmInputSamplingReportSaved,
  kKbmInputSamplingReportFailed,
  kKbmInputSamplingNoReport,
  kKbmBindGuide,
  kKbmBindDpadLeft,
  kKbmBindDpadRight,
  kKbmBindDpadDown,
  kKbmBindDpadUp,
  kKbmBindLThumbLeft,
  kKbmBindLThumbRight,
  kKbmBindLThumbDown,
  kKbmBindLThumbUp,
  kKbmBindLThumbPress,
  kKbmBindRThumbUp,
  kKbmBindRThumbDown,
  kKbmBindRThumbRight,
  kKbmBindRThumbLeft,
  kKbmBindRThumbPress,
  kKbmBindX,
  kKbmBindB,
  kKbmBindA,
  kKbmBindY,
  kKbmBindLTrigger,
  kKbmBindRTrigger,
  kKbmBindBack,
  kKbmBindStart,
  kKbmBindLShoulder,
  kKbmBindRShoulder,
  kMouseCaptureEnabled,
  kMouseCaptureReleased,
  kMouseCaptureLocked,
  kMouseCaptureHotkey,
  kMouseCaptureReturned,

  kHotkeysTitle,
  kHotkeysGameplay,
  kHotkeysDisabledSuffix,
  kHotkeyAReadbackResolve,
  kHotkeyBToggleLogging,
  kHotkeyYToggleFullscreenGuide,
  kHotkeyXClearMemoryPageState,
  kHotkeyRightShoulderClearGpuCache,
  kHotkeyLeftShoulderToggleVibration,
  kHotkeyDpadDownHalfCpuScalar,
  kHotkeyDpadUpDoubleCpuScalar,
  kHotkeyDpadRightResetCpuScalar,
  kHotkeyYToggleFullscreen,
  kHotkeyStartRunSelectedTitle,
  kHotkeyBackStartToggleLogging,
  kHotkeyDpadDownNextTitle,
  kHotkeyDpadUpPreviousTitle,
  kHotkeysReadbackResolve,
  kHotkeysClearMemoryPageState,
  kHotkeysControllerHotkeys,
  kHotkeysEnabled,
  kHotkeysDisabled,
  kHotkeysTitleSelection,

  kConsoleTitle,
  kUnknown,
  kConsoleResolution,
  kConsoleTimezone,
  kConsoleUser,
  kConsoleTime,
  kConsoleDisableDst,
  kConsole24Hour,
  kConsoleLocale,
  kConsoleLanguage,
  kConsoleCountry,
  kConsoleProfile,
  kConsoleDefaultProfile,
  kConsoleParentalControl,
  kConsoleRetailOptions,
  kConsoleDashboardInitialized,
  kConsoleIptvInitialized,
  kConsoleDvrInitialized,
  kConsoleKinectInitialized,
  kConsoleSystem,
  kConsoleVideoOptions,
  kConsoleAvRegion,
  kConsoleWidescreen,
  kConsoleAudioOptions,
  kConsoleMono,
  kConsoleLowLatencyUnsupported,
  kConsoleAudioPlayerVolume,
  kConsoleNetwork,
  kConsoleMacAddress,
  kConsoleNetworkId,
  kConsoleSave,
  kConsoleSaved,
  kConsoleReset,
  kGuestLanguageEnglish,
  kGuestLanguageJapanese,
  kGuestLanguageGerman,
  kGuestLanguageFrench,
  kGuestLanguageSpanish,
  kGuestLanguageItalian,
  kGuestLanguageKorean,
  kGuestLanguageTraditionalChinese,
  kGuestLanguagePortuguese,
  kGuestLanguagePolish,
  kGuestLanguageRussian,
  kGuestLanguageSwedish,
  kGuestLanguageTurkish,
  kGuestLanguageNorwegian,
  kGuestLanguageDutch,
  kGuestLanguageSimplifiedChinese,

  kCount,
};

Language GetLanguage();
bool IsTraditionalChinese();
void SetLanguage(Language language, bool save_config = true);
const char* Get(StringId id);

}  // namespace xe::app::localization

#endif  // XENIA_APP_LOCALIZATION_H_
