/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Copyright 2026 Xenia Canary. All rights reserved.                          *
 * Released under the BSD license - see LICENSE in the root for more details. *
 ******************************************************************************
 */

#ifndef XENIA_APP_LOCALIZATION_H_
#define XENIA_APP_LOCALIZATION_H_

#include <cstdint>

namespace xe::app::localization {

enum class Language : uint8_t {
  kEnglish,
  kTraditionalChinese,
};

// Stable identifiers keep translations independent of the English wording.
enum class StringId : uint16_t {
  kMenuFile,
  kMenuOpenRecent,
  kMenuZarPackage,
  kMenuOpen,
  kMenuInstallContent,
  kMenuCreate,
  kMenuExtract,
  kMenuClose,
  kMenuShowContentDirectory,
  kMenuExit,
  kMenuProfile,
  kMenuShowProfile,
  kMenuCpu,
  kMenuResetTimeScalar,
  kMenuHalfTimeScalar,
  kMenuDoubleTimeScalar,
  kMenuToggleProfiler,
  kMenuPauseProfiler,
  kMenuGuestDebugger,
  kMenuHostDebugger,
  kMenuGpu,
  kMenuTraceFrame,
  kMenuClearRuntimeCaches,
  kMenuDisplay,
  kMenuPostProcessing,
  kMenuFullscreen,
  kMenuScreenshot,
  kMenuWinKey,
  kMenuWinKeySettings,
  kMenuHid,
  kMenuControllerVibration,
  kMenuControllerHotkeys,
  kMenuXmp,
  kMenuShowXmp,
  kMenuConsole,
  kMenuConsoleSettings,
  kMenuUi,
  kMenuInterfaceLanguage,
  kLanguageEnglish,
  kLanguageEnglishActive,
  kLanguageTraditionalChinese,
  kLanguageTraditionalChineseActive,
  kMenuHelp,
  kMenuFaq,
  kMenuCompatibility,
  kMenuBuildCommit,
  kMenuRecentChanges,
  kMenuAbout,

  kProfileTitle,
  kProfileNoProfilesTitle,
  kProfileNoProfilesMessage,
  kProfileCreate,
  kProfileCreateMigrate,
  kProfileOpenMenu,
  kProfileNoProfiles,
  kProfileLogin,
  kProfileLoginToSlot,
  kProfileSlot,
  kProfileLogout,
  kProfileModify,
  kProfilePlayedTitles,
  kProfileContentDirectory,
  kProfileDelete,
  kProfileDeleteWarning,
  kProfileConfirmDelete,
  kProfileUser,
  kProfileAssignedSlot,
  kProfileNotSignedIn,

  kPostTitle,
  kPostAnyGpu,
  kPostAntiAliasing,
  kPostNone,
  kPostFxaaNormal,
  kPostFxaaExtreme,
  kPostResamplingSharpening,
  kPostNoneBilinear,
  kPostCas,
  kPostFsr,
  kPostBilinearDescription,
  kPostCasDescription,
  kPostFsrDescription,
  kPostFxaaRecommended,
  kPostFsrSharpnessReduction,
  kPostCasSharpnessFsr,
  kPostCasSharpness,
  kPostReset,
  kPostDithering,
  kPostDither8bpc,

  kWinKeyTitle,
  kWinKeyBackendInactive,
  kWinKeyPressBinding,
  kWinKeyBindingTooltip,
  kWinKeyAddAlternativeBinding,
  kWinKeyClearBinding,
  kWinKeyKeyboard,
  kWinKeyModeDisabled,
  kWinKeyModeController,
  kWinKeyModePassthrough,
  kWinKeyKeyboardMode,
  kWinKeyControllerSlot,
  kWinKeyPlayer1,
  kWinKeyPlayer2,
  kWinKeyPlayer3,
  kWinKeyPlayer4,
  kWinKeyBindingHelp,
  kWinKeyXboxInput,
  kWinKeyKeyboardMouse,
  kWinKeyPassthroughHelp,
  kWinKeyMouse,
  kWinKeyEnableRawMouse,
  kWinKeyRawMouseRequiresController,
  kWinKeySensitivity,
  kWinKeySensitivityGuide,
  kWinKeyInvertVertical,
  kWinKeyCaptureOnStart,
  kWinKeyCaptureToggle,
  kWinKeyFineTuning,
  kWinKeyAimCurve,
  kWinKeyAimCurveHelp,
  kWinKeyCompensateGameDeadzone,
  kWinKeyMinimumResponse,
  kWinKeyMinimumResponseHelp,
  kWinKeyFullStickThreshold,
  kWinKeyFullStickHelp,
  kWinKeyDiagnostics,
  kWinKeyLastStickOutput,
  kWinKeyMaximum,
  kWinKeyRawSpeed,
  kWinKeyRawInputCapture,
  kWinKeyReady,
  kWinKeyOff,
  kWinKeyActive,
  kWinKeyReleased,
  kWinKeyInputPaused,
  kWinKeyDiagnosticsUnavailable,
  kWinKeySave,
  kWinKeyCancel,
  kWinKeyResetAll,
  kWinKeySettingsFile,
  kWinKeySaveFailed,
  kMouseCaptureEnabled,
  kMouseCaptureReleased,
  kMouseCaptureLocked,
  kMouseCaptureHotkey,
  kMouseCaptureReturned,

  kHotkeysTitle,
  kHotkeysGameplay,
  kHotkeysDisabledSuffix,
  kHotkeyAReadbackResolve,
  kHotkeyBToggleLogging,
  kHotkeyYToggleFullscreenGuide,
  kHotkeyXClearMemoryPageState,
  kHotkeyRightShoulderClearGpuCache,
  kHotkeyLeftShoulderToggleVibration,
  kHotkeyDpadDownHalfCpuScalar,
  kHotkeyDpadUpDoubleCpuScalar,
  kHotkeyDpadRightResetCpuScalar,
  kHotkeyYToggleFullscreen,
  kHotkeyStartRunSelectedTitle,
  kHotkeyBackStartToggleLogging,
  kHotkeyDpadDownNextTitle,
  kHotkeyDpadUpPreviousTitle,
  kHotkeysReadbackResolve,
  kHotkeysClearMemoryPageState,
  kHotkeysControllerHotkeys,
  kHotkeysEnabled,
  kHotkeysDisabled,
  kHotkeysTitleSelection,

  kConsoleTitle,
  kUnknown,
  kConsoleResolution,
  kConsoleTimezone,
  kConsoleUser,
  kConsoleTime,
  kConsoleDisableDst,
  kConsole24Hour,
  kConsoleLocale,
  kConsoleLanguage,
  kConsoleCountry,
  kConsoleProfile,
  kConsoleDefaultProfile,
  kConsoleParentalControl,
  kConsoleRetailOptions,
  kConsoleDashboardInitialized,
  kConsoleIptvInitialized,
  kConsoleDvrInitialized,
  kConsoleKinectInitialized,
  kConsoleSystem,
  kConsoleVideoOptions,
  kConsoleAvRegion,
  kConsoleWidescreen,
  kConsoleAudioOptions,
  kConsoleMono,
  kConsoleLowLatencyUnsupported,
  kConsoleAudioPlayerVolume,
  kConsoleNetwork,
  kConsoleMacAddress,
  kConsoleNetworkId,
  kConsoleSave,
  kConsoleSaved,
  kConsoleReset,
  kGuestLanguageEnglish,
  kGuestLanguageJapanese,
  kGuestLanguageGerman,
  kGuestLanguageFrench,
  kGuestLanguageSpanish,
  kGuestLanguageItalian,
  kGuestLanguageKorean,
  kGuestLanguageTraditionalChinese,
  kGuestLanguagePortuguese,
  kGuestLanguagePolish,
  kGuestLanguageRussian,
  kGuestLanguageSwedish,
  kGuestLanguageTurkish,
  kGuestLanguageNorwegian,
  kGuestLanguageDutch,
  kGuestLanguageSimplifiedChinese,

  kCount,
};

Language GetLanguage();
bool IsTraditionalChinese();
void SetLanguage(Language language, bool save_config = true);
const char* Get(StringId id);

}  // namespace xe::app::localization

#endif  // XENIA_APP_LOCALIZATION_H_
